export const types = Object.freeze({
  // Sync
  FILTERS_SELECT_CLOUDY: 'FILTERS_SELECT_CLOUDY',
  FILTERS_SELECT_SUNNY: 'FILTERS_SELECT_SUNNY',
  FILTERS_SELECT_MIN_TEMP: 'FILTERS_SELECT_MIN_TEMP',
  FILTERS_SELECT_MAX_TEMP: 'FILTERS_SELECT_MAX_TEMP',
  FILTERS_FILTERED: 'FILTERS_FILTERED',
  FILTERS_RESET: 'FILTERS_RESET',
  FILTERS_FILL: 'FILTERS_FILL',
  FILTERS_ERROR: 'FILTERS_ERROR',
  FILTERS_SET_SELECTED_DAY: 'FILTERS_SET_SELECTED_DAY',
});